services:
  postgres:
    image: postgres:latest
    platform: linux/amd64
    container_name: postgresAgro
    restart: unless-stopped
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: agriculture
    volumes:
      - pgdata:/var/lib/postgresql1
      - ./tables/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pguser -d agriculture']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
